{% set name = "cellfinder-core" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cellfinder-core-{{ version }}.tar.gz
  sha256: c1fc9da659d40043a97b970104c75cace21582aa25e31b64fec53c2b6dc26201

build:
  noarch: python
  entry_points:
    - cellfinder_download = cellfinder_core.download.cli:main
    - cellfinder_train = cellfinder_core.train.train_yml:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - dask
    - fancylog >=0.0.7
    - brainglobe-utils
    - natsort
    - numba
    - numpy
    - python >={{ python_min }},<3.11
    - scikit-image
    - scikit-learn
    - scipy
    - tifffile
    - tqdm
    - __unix  # [unix]
    - tensorflow >=2.5.0, <2.12.0  # [unix]
    - __win  # [win]

test:
  imports:
    - cellfinder_core  # [unix]
  commands:
    - pip list
    - pip check  # [unix]
    - cellfinder_download --help  # [unix]
    - cellfinder_train --help  # [unix]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://brainglobe.info/cellfinder
  summary: Automated 3D cell detection in large microscopy images
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/cellfinder-core

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
