{% set name = "cellfinder-core" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cellfinder-core-{{ version }}.tar.gz
  sha256: 7b107a368903e0470ea7b89b8d2353622db2f455ad1f01f427f64a5c2b8efbec

build:
  entry_points:
    - cellfinder_download = cellfinder_core.download.cli:main
    - cellfinder_train = cellfinder_core.train.train_yml:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - cython
    - pip
    - python
  run:
    - dask
    - fancylog >=0.0.7
    - imlib >=0.0.26
    - natsort
    - numpy
    - python
    - scikit-image
    - scikit-learn
    - tensorflow >=2.5.0
    - tifffile
    - tqdm


test:
  imports:
    - cellfinder_core
  commands:
    - pip list
    - pip check  # [unix]
    - cellfinder_download --help
    - cellfinder_train --help
  requires:
    - pip

about:
  home: https://brainglobe.info/cellfinder
  summary: Automated 3D cell detection in large microscopy images
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/cellfinder-core

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
