{% set name = "cellfinder-core" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cellfinder-core-{{ version }}.tar.gz
  sha256: d4baa7d97b082937d9ead3f6a4ab3912118cf911ea72ea14a57ed7fdb3fb0c2b

build:
  noarch: python
  entry_points:
    - cellfinder_download = cellfinder_core.download.cli:main
    - cellfinder_train = cellfinder_core.train.train_yml:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8, <3.11
    - setuptools_scm
  run:
    - dask
    - fancylog >=0.0.7
    - imlib >=0.0.26
    - natsort
    - numba
    - numpy
    - python >=3.8, <3.11
    - scikit-image
    - scikit-learn
    - tifffile
    - tqdm
    - __unix  # [unix]
    - tensorflow >=2.5.0, <2.12.0  # [unix]
    - __win  # [win]


test:
  imports:
    - cellfinder_core  # [unix]
  commands:
    - pip list
    - pip check  # [unix]
    - cellfinder_download --help  # [unix]
    - cellfinder_train --help  # [unix]
  requires:
    - pip

about:
  home: https://brainglobe.info/cellfinder
  summary: Automated 3D cell detection in large microscopy images
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/cellfinder-core

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
